export default {
  UPDATE_USER: 'UPDATE_USER',
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',

  SET_OFFIMP_LIST: 'SET_OFFIMP_LIST',
  SET_OFFIMP_POLLINGLIST: 'SET_OFFIMP_POLLINGLIST',
  SET_OFFIMP_TASK_STATUS: 'SET_OFFIMP_TASK_STATUS',
  CLEAR_OFFIMP_TIMER: 'CLEAR_OFFIMP_TIMER',
  START_OFFIMP_TASK: 'START_OFFIMP_TASK',
  DELETE_OFFIMP_TASK: 'DELETE_OFFIMP_TASK',
  SET_OFFIMP_DETAIL_LIST: 'SET_OFFIMP_DETAIL_LIST'
}
