export default {
  // 登录
  SET_USER: 'SET_USER',

  // 离线导入
  SET_OFFIMP_LIST: 'SET_OFFIMP_LIST',
  SET_OFFIMP_TASK_STATUS: 'SET_OFFIMP_TASK_STATUS',
  CLEAR_OFFIMP_TIMER: 'CLEAR_OFFIMP_TIMER',
  START_OFFIMP_TASK: 'START_OFFIMP_TASK',
  DELETE_OFFIMP_TASK: 'DELETE_OFFIMP_TASK',
  SET_OFFIMP_DETAIL_LIST: 'SET_OFFIMP_DETAIL_LIST',
  SET_OFFIMP_DETAIL_TASK_STATUS: 'SET_OFFIMP_DETAIL_TASK_STATUS',
  CLEAR_OFFIMP_DETAIL_TIMER: 'CLEAR_OFFIMP_DETAIL_TIMER',

  // 定时导入
  SET_INCIMP_LIST: 'SET_INCIMP_LIST',
  SET_INCIMP_DETAIL_LIST: 'SET_INCIMP_DETAIL_LIST',

  // 离线导出
  SET_OFFEXP_LIST: 'SET_OFFEXP_LIST',
  SET_OFFEXP_DETAIL_LIST: 'SET_OFFEXP_DETAIL_LIST',
  SET_OFFEXP_DETAIL_STATUS: 'SET_OFFEXP_DETAIL_STATUS',
  CLEAR_OffEXP_DETAIL_TIMER: 'CLEAR_OffEXP_DETAIL_TIMER',

  // 数据源
  SET_SOURCE_LIST: 'SET_SOURCE_LIST',

  // 通用
  SET_DATA_SOURCE: 'SET_DATA_SOURCE',
  SET_SOURCE_TABLE: 'SET_SOURCE_TABLE',

  // 数据处理
  HANDLE_SET_DB_LIST: 'HANDLE_SET_DB_LIST',
  HANDLE_SET_TB_LIST: 'HANDLE_SET_TB_LIST',
  HANDLE_SET_TB_INFO: 'HANDLE_SET_TB_INFO',
  HANDLE_RUN_SQL: 'HANDLE_RUN_SQL',

  // 数据管理
  SET_ANALYSIS_LIST: 'SET_ANALYSIS_LIST',

  // 运维中心
  SET_LOG_LIST: 'SET_LOG_LIST',
  SET_USER_LIST: 'SET_USER_LIST',
  SET_RESOURCE_LIST: 'SET_RESOURCE_LIST',

  // 全选测试
  SELECT_TEST: 'SELECT_TEST'
}
